---
title: "Käyttöliittymä"
output: 
   html_document:
    theme: spacelab
runtime: shiny
---

</br>


```{r eurostat, echo=FALSE, echo=FALSE, eval=FALSE}

source("eurostat_package/firstlib.R")
source("eurostat_package/get_eurostat.R")
source("eurostat_package/getEurostatDictionary.R")
source("eurostat_package/get_eurostat_raw.R")
source("eurostat_package/getEurostatTOC.R")
source("eurostat_package/grepEurostatTOC.R")
source("eurostat_package/label_eurostat.R")
source("eurostat_package/setEurostatTOC.R")
source("eurostat_package/tidyr_functions.R")
# kirjastot
library(plyr)

```



### Etsi sopivia datoja


```{r, echo=FALSE, eval=FALSE}

shinyApp(
  ui = fluidPage(
    
  
      inputPanel(
          textInput("phrase", 
            label = h4("Kirjoita tähän englanniksi kiinnostava hakutermi"),
            value = "health care"),
  
                      radioButtons("tyyppi", h4("Valitse data/taulukko"),
                                c("Dataset"="dataset",
                                  "Table"="table")),
  
          submitButton("Päivitä!", icon("refresh"))
              ),
                  
                  
    mainPanel(
                  tableOutput("taulukko")
      )
  
  
    ),
  
  server = function(input, output) {
    


    output$taulukko <- renderTable({
      tbl <- grepEurostatTOC(pattern=input$phrase, type=input$tyyppi)
      tbl
      })
    


} , options = list(height = 550)
)
    
  
```


### Hae data Eurostatilta


```{r, echo=FALSE, eval=FALSE}

shinyApp(
  ui = fluidPage(
    
    inputPanel(
          textInput("code", 
            label = h4("Kopioi <code> kentän koodi tähän"),
            value = "hlth_sha1m"),
  
#   radioButtons("muoto", h4("Valitse data/taulukko"),
#                                 c("Pitkä"="long",
#                                   "Leveä"="wide")),
  
#   radioButtons("labelling", h4("Tarkemmat tunnisteet"),
#                                 c("Ei "="label_no",
#                                   "Kyllä"="label_yes")),

  submitButton("Päivitä!", icon("refresh"))
      ),
  
  
        tabsetPanel(
                  tabPanel("Taulukon ekat 6 riviä", tableOutput("taulukko")), 
                  tabPanel("summary(data)", verbatimTextOutput("summary")), 
                  tabPanel("str(data)", verbatimTextOutput("str"))
      )
  
    ),
  
  server = function(input, output) {
    
    dataInput <- reactive({
          tbl <- get_eurostat(id=input$code)
          #if (input$labelling == "label_no" )  tbl <- tbl
          #if (input$labelling == "label_yes" ) {
          label_eurostat(tbl)
          #}
        })
    
    

    output$taulukko <- renderTable({
      tbl <- dataInput()
      rbind(head(tbl,3),tail(tbl,3))
    })
    
      output$summary <- renderPrint({
      tbl <- dataInput()
      summary(tbl)
    })
    
      output$str <- renderPrint({
        tbl <- dataInput()
        str(tbl)
      })
  
  

  

},
options = list(height = 550))
    
  
```




### Piirrä kuvio

```{r, echo=FALSE, eval=FALSE, eval=FALSE}

shinyApp(
  ui = fluidPage(
    
      sidebarLayout(
    
    sidebarPanel(
      
          textInput("code", 
            label = h4("Kopioi <code> kentän koodi tähän"),
            value = "hlth_sha1m"),
          
#           sliderInput("ncolumns", "Montako saraketta datassa on?",
#                              min = 4, max = 6, value = 4),

              uiOutput("ui_col1"),
              uiOutput("ui_col2"),
              uiOutput("ui_col3"),
              #uiOutput("ui_geo"),

          submitButton("Päivitä!", icon("refresh"))
      
      ),
                  
                  
        mainPanel(
                  #tabPanel("summary(data)", verbatimTextOutput("table")), 
                  plotOutput("kuvio")
      )
    )
    ),
  
  server = function(input, output) {
    
    
        dataInput <- reactive({
          tbl <- get_eurostat(id=input$code)
          label_eurostat(tbl)
        })
        
        

        
        #if (input$ncolumns >= 4) {
        output$ui_col1 <- renderUI({
            
                  tbl <- dataInput()
                  #tbl <- tbl[ , -which(names(tbl) %in% c("geo","time","value"))]
                  levelit1 <- levels(tbl[[1]])
                  # levels
                  selectInput("col1", h4("Valitse 1. sarakkeen luokka"),
                              choices = levelit1)
                  })
        #}
        
        #if (input$ncolumns >= 5) {
          
          output$ui_col2 <- renderUI({
            
                  tbl <- dataInput()
                  #tbl <- tbl[ , -which(names(tbl) %in% c("geo","time","value"))]
                  levelit2 <- levels(tbl[[2]])
                  
                  selectInput("col2", h4("Valitse 2. sarakkeen luokka"), 
                              choices = levelit2)
                  
                 })
        
        #  }
        
        
        #if (input$ncolumns >= 6) {
          output$ui_col3 <- renderUI({
            
                  tbl <- dataInput()
                  #tbl <- tbl[ , -which(names(tbl) %in% c("geo","time","value"))]
                  levelit3 <- levels(tbl[[3]])
                  
                  selectInput("col3", h4("Valitse 3. sarakkeen luokka"), 
                              choices = levelit3)
                  
                  })
         # }
#         output$ui_geo <- renderUI({
#             
#                   tbl <- dataInput()
#                   lev_geo <- levels(tbl[["geo"]])
#                   
#                   selectInput("geo", "Valitse geo",
#                               choices = lev_geo)
#                   })
        

    
    output$table <- renderPrint({
      c(input$col1,input$col2,input$col3)
      
      
    })

    
    output$kuvio <- renderPlot({
    
        tbl <- dataInput()
      
        tbl$time <- as.factor(tbl$time)
        tbl$time <- as.numeric(levels(tbl$time))[tbl$time]
        tbl <- tbl[!is.na(tbl$value),]
        
        tbl <- tbl[tbl[1] == input$col1,]
        tbl <- tbl[tbl[2] == input$col2,]
        tbl <- tbl[tbl[3] == input$col3,]
    
      library(ggplot2)
      ggplot(tbl, aes(x=time,y=value,
                  color=geo,group=geo)) +
          geom_point() + 
          geom_line() +
          theme(legend.position="none") +
          geom_text(data=merge(tbl, aggregate(time ~ geo, tbl, max),
                       by=c("time","geo")),
            aes(x=time, y = value, label=geo),
            hjust=-0.5,vjust=-1,size=4) 
  
})
    

},
options = list(height = 750))
    
  
```


